### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by eisengrau** [PabloSzx/stream-phones#1]
Hi,

Man, I wish I had this years ago, I was working with some phones with a busted screen, and been struggling with some kind of a Java based screen mirroring crap which either worked or not. Your app instantly opens and does it's thing. Thank you!

**Comment by PabloSzx** [comment]
You are welcome 😄 

I'm amazed you could even find this small project, I didn't even add a README to this repo, I just did 😃

**Comment by eisengrau** [comment]
I was actually searching for "adb timelapse" or "adb camera control" or similar, and it came up in the results. I would like to create some sort of an timelapse/cctv camera system out of my old phones. There are only legacy/non-working binaries floating around github/xda forums, none of them are stable, good enough unfortunately. There was one called "mobilewebcam" which had all the features that I needed (take timed photo, resart phone, run app at startup, send jpegs over the network), but it's dead since like 7 years, and it's non functional on newer android/lineageos versions.
